# ERCA 2024 mini-paper group 5: Snow?

In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [5]:
path_to_data = r'Data/data_monthly_DE_DWD.csv'
# read data
snow_data = pd.read_csv(path_to_data)
# snow depth (HS), depth of snowfall (HN, also denoted as fresh snow or snowfall), 
# snow water equivalent (SWE), snow cover area (SCA), and snow cover duration (SCD)

In [3]:
snow_data

,Name,year,month,HNsum,HSmean,HSmax,SCD1,SCD1gt,SCD10,SCD20,...,HSmean_gapfill,frac_gapfilled,HSmax_gapfill,SCD1_gapfill,SCD1gt_gapfill,SCD10_gapfill,SCD20_gapfill,SCD30_gapfill,SCD50_gapfill,SCD100_gapfill
0,Aach,1937,1,NaN,0.161290,5.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aach,1937,2,NaN,0.857143,10.0,5.0,5.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aach,1937,3,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aach,1937,4,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aach,1937,5,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532747,Zwiefalten,2008,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
532748,Zwiefalten,2008,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
532749,Zwiefalten,2008,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
532750,Zwiefalten,2008,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.066667,1.0,9.0,9.0,7.0,0.0,0.0,0.0,0.0,0.0
532751,Zwiefalten,2008,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.645161,1.0,14.0,19.0,12.0,6.0,0.0,0.0,0.0,0.0